sudo: required
dist: trusty
language: c
script:
  - make distclean && make CC=gcc MODE=release && make test
  - make distclean && make CC=gcc MODE=debug && make test
  - make distclean && make CC=gcc MODE=static && make test
  - make deploy
deploy:
  provider: releases
  api_key:
    secure: E+zOJJe4A7NIJ90/8Xq7j1IHsKuZU45keGZlK4YODPuiw4xkEm5Z1zzkmGTxHOXATtk7FRs5ajK2gVOWtLV3KOV1MD1O0PhiQgikNondtf14l5bj2RI9nmBzSUbTaI9C2VCcIN8PxOSwlM3dsxS/u4wfgA9S+e2WhJ9HQH5qvKeRovHAgz6oe8097Iblm5mASDXWKBrkky4Eh9F17T2MXSIagdvrWIaZIZfSn8YeeaySvRL+VcQIClIa4PhDY9F3w7K3R1Y4t5RUZWBI36CvNUGh6GdejoTlKookfJ1L6BE1ttO3taoRetPXnoPJJccxlJeIoP8QukzpcLJywEjnDjw7Oy4B2lGohuq/rFzHYxNBi3a8fLXDgEzWJdZW/yVMAkZCIAvUZBu4QqsbuQGkbgJvkl6LmWw13uknoz9kIa8p9Xp6wfddVBHQC7xD9PMDbR+Sdj1FOMgGS7OAcmKqcZloJzY34MU4NrWTnaXvWmg9qXXMMilUUMJ/+mJDNHwvcmAYWjX7lWhRWlPMjW+bF8Xft7J0OzzHlrfvsQtpGr4+Qsw0qFbzLLBVugFgPJnKa1gSiHQssuq3wQsoHSAzrSt7FJXfaKAeLvpA5WVxgfW1xEhdEZrmJ/yd3fV4DFFXRJc3FrQKrOLiN41Ug/J8SEi/faUL29Wmb7HCGmQFj2c=
  file:
    - deploy/bin/ckains.x86_64
    - deploy/bin/ckains.i686
  on:
    repo: mickael-guene/ckains
    tags: true
